version: '3.8'
services:
  angular-monorepo:
    container_name: angular-monorepo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    command: yarn nx serve angular-monorepo --host 0.0.0.0 --port 4200
